function neff = Calcneff(rindexx,dx)

% This function calculates the effective refractive index
% for the Quantum Cascade Laser
%
% USAGE:
%
% neff = Calcneff(rindexx,dx)
%
% INPUT:
%
% rindexx - refractive index mesh (generated by QCLmesh.m)
% dx - grid spacing
%
% OUTPUT:
%
% neff - effective refractive index
%
% Author - Muhammad Anisuzzaman Talukder (anisuzzaman@umbc.edu)
%--------------------------------------------------------------
%
% Theory
% neff = integrate[n(x)dx]/integrate(dx)
% neff = [n1x1+n2x2+ ... +nnxn]/[x1+x2+ ... +xn]
% n1,n2, ... ,nn are the refractive indices of the layers
% x1,x2, ... ,xn are the thicknesses of the layers

nx = length(rindexx);

N = 0;
X = 0;

for ii = 1 : nx
    N = N + rindexx(ii) * dx;
    X = X + dx;
end

neff = N/X;